### ISSUE TITLE
A few unknown properties identified

### ISSUE THREAD

**Issue by MichaelTheriot** [villermen/runescape-cache-tools#83]
- `properties.unknown824` - if the item is unbankable, this value is presented instead of the default reason
- `properties.unknown1264` - appears to be a duplicate of the first inventory option; maybe there is another function
- `properties.unknown1264` - appears to be a duplicate of the second inventory option
- `properties.unknown2522` - the construction materials required to build
- `properties.unknown1211` - equip option 5 (some items like Wicked hood can override this with more information)
- `properties.unknown6712` - equip option 6
- `properties.unknown6713` - equip option 7
- `properties.unknown690` - the warning provided on the Hand cannon; I don't own one to see how this warning manifests in the client
- `properties.unknown5854` - appears to be the plural form of the item name; only seems to be used by Wushanko items, possibly for some description when trading with NPCs

**Comment by villermen** [comment]
In arbitrary order:

1. I've named property 824 to `UnbankableMessage` and added property 59 as `Unbankable` based on findings. 001413d
2. I've named property 690 to `UnusedHandCannonTooltip` because it seems to only assigned to this one item with no mention of it in-game. 9ed012d
3. I might have figured out what property 1264 and 1265 are used for. The options that an item has in the bank inventory are different from its regular options. These are most likely those (can be checked with large rune pouch for example). I've named them `BankInventoryOption1` and `BankInventoryOption2`. Properties before and after seem to be unused for now. 4a6719b
4. Additional equip options go to 8 (!) for a select few items. One of which is the wilderness sword (4). 94a4605
5. Remaining properties were introduced pretty much as described in #85.

@MichaelTheriot I'll release a new (minor) version of the tool when #82 gets resolved.
